---
title: "About"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE,message=FALSE)
```

The fictitious Kronos Incident saw the disappearance of several employees of the Tethys-based GASTech company in January 2014 after a successful initial public offering (IPO) of the company. Given that GASTech has not been very environmentally friendly in its operations of a natural gas production site in the island country of Kronos, it was suspected that a Kronos-based organization (POK) is involved in the disappearance of the employees, as a form of retaliation. In order to have a better idea on what exactly transpired to lead to the vanishing of the GASTech employees, we will be applying visual analytic techniques on the datasets provided.

This study will be handling visualizations on newspaper articles, employee records and emails, call center reports and microblog tweets in an interactive web application. Users can explore the application and understand more about GASTech's reputation and how events unfolded that lead to the kidnappings of employees.

The interactive Shiny app aims to provide information on:

1. Media portrayal of GASTech over the years
2. Relationships among GASTech, POK, the APA and Government
3. Meaningful event reports during the incident day
4. Risks identified during the incident day and their corresponding locations
